models/topic.py
from sqlalchemy import Integer, Column, UnicodeText, Unicode
from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def add(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

    @classmethod
    def all_current_user_topic(cls, user_id):
        """
        返回所有当前用户创建过的话题
        """
        ms = Topic.all()
        user_topics = []
        for t in ms:
            # 用户id与帖子是否id一致
            if t.user().id == user_id:
                user_topics.append(t)
        # 逆序topics使其排列从最近发表的开始
        user_topics.reverse()
        return user_topics

    @classmethod
    def all_replied_topic(cls, user_id):
        """
        返回所有当前用户回复过的话题
        """
        ms = Topic.all()
        replied_topics = []
        # all_lasted_replies存放当前用户每一个话题下时间最近的一条回复
        all_lasted_replies = []
        for t in ms:
            # replies存放用户在当前话题下所有的回复
            replies = []
            for r in t.replies():
                if r.user().id == user_id:
                    replies.append(r)
            # 对所有当前用户在当前话题下的回复按修改时间降序排序
            if replies:
                replies.sort(key=lambda x: x.updated_time, reverse=True)
                lasted_reply = replies[0]
                all_lasted_replies.append(lasted_reply)
        # 对每一个话题下最近的一条回复按时间降序排列
        all_lasted_replies.sort(key=lambda x: x.updated_time, reverse=True)
        for r in all_lasted_replies:
            # 找到每一条回复对应的话题
            replied_topics.append(cls.one(id=r.topic_id))
        return replied_topics

    def last_reply_user(self):
        """
        返回所有当前话题下最后一个回复的用户，没有的话返回话题作者用户
        """
        replies = [r for r in self.replies()]
        print('replies', replies)
        if replies:
            replies.sort(key=lambda x: x.updated_time, reverse=True)
            last_reply = replies[0]
            return last_reply.user()
        else:
            return self.user()

routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
)
from models.user import User
from models.topic import Topic
from models.board import Board
from routes import current_user, new_csrf_token
import os
import uuid


main = Blueprint('index', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    u = current_user()
    return render_template("topic/index.html", user=u, ms=ms, token=token, bs=bs, bid=board_id)


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login user <{}>'.format(u))
    if u is None:
        return redirect(url_for('bp_topic.index'))
    else:
        session['user_id'] = u.id
        session.permanent = True
        return redirect(url_for('.index'))


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        user_topics = Topic.all_current_user_topic(u.id)
        replied_topics = Topic.all_replied_topic(u.id)
        # for t in user_topics:
        #     u = t.last_reply_user()
        #     print('last reply user', u, u.image)
        board_id = int(request.args.get('board_id', -1))
        return render_template('profile.html', user=u, ms=user_topics, rs=replied_topics, bid=board_id)


@main.route('/setting')
def setting():
    u = current_user()
    return render_template('setting.html', user=u)


@main.route('/change_setting', methods=['POST'])
def change_setting():
    form = request.form.to_dict()
    u = current_user()
    # 修改密码
    if 'old_pass' in form:
        old_pass = User.salted_password(form['old_pass'])
        if u.password == old_pass:
            new_pass = User.salted_password(form['new_pass'])
            User.update(u.id, password=new_pass)
    # 更改其它信息
    else:
        print('user_info', form)
        User.update(u.id, **form)
    return redirect(url_for('.profile'))


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file = request.files['avatar']

    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('static/avatar/', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/static/avatar/{}'.format(filename))

    return redirect(url_for('.profile'))


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.find(id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


def not_found(e):
    return render_template('404.html')

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.reply import Reply


main = Blueprint('bp_reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    print('DEBUG', form)
    m = Reply.add(form, user_id=u.id)
    return redirect(url_for('bp_topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user, csrf_required, new_csrf_token
from models.topic import Topic
from models.board import Board


main = Blueprint('bp_topic', __name__)


@main.route("/")
def index():
    u = current_user()
    return render_template("/index.html", user=u)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    return render_template("topic/detail.html", topic=m)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)

templates/topic/detail.html
{% extends "/base.html" %}
{% block title %} {{ topic.title }} {% endblock%}
{% block main %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 {{ topic.created_time | format_time }}
            </span>
            <span>
                作者
                <a href="{{ url_for('index.profile')}}">
                {{ topic.user().username }}
                </a>
                {# 作者 {{ User.one(id=topic.user_id).username }} #}
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 问答
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        {% set u = r.user() %}
        <div class='cell reply_area reply_item'>
            <div class='user_info'>
                <a class='dark reply_author'>
                    {{ u.username }}
                </a>
                <a class="reply_time">
                    {{ loop.index }}楼 / {{ loop.length }}楼 •
                    <span class="time" data-created_time="{{ r.created_time }}"></span>
                </a>
            </div>
            <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
            </div>
            <div class='reply_content from-{{ u.username }}'>
                <div class="markdown-text">{{ r.content }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div>
        <form action="{{ url_for('bp_reply.add') }}" method="post">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea name="content"></textarea>
            <button>添加回复</button>
        </form>
    </div>
</div>
{% endblock%}

{% block endscript %}
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var registerTimer = function () {
        setInterval(function () {
            var times = es('.time')
            for (var i = 0; i < times.length; i++) {
                var t = times[i]
                var time = Number(t.dataset.created_time)
                var now = Math.floor(new Date() / 1000)
                var delta = now - time
                var s = `${delta} 秒前`
                t.innerText = s
            }
        }, 1000)
    }

    var __main = function () {
        markContents()
        highlight()
        registerTimer()
    }

    __main()

</script>
{% endblock %}

templates/topic/index.html
{% extends "/base.html" %}
{% block title %}bbs club{% endblock%}
{% block main %}
<div id="main">
    <div id="sidebar">
        <div class='panel'>

            <div class='header'>
                <span class='col_fade'>个人信息</span>
            </div>
            <div class='inner'>
                <div class='user_card'>
                    <div>
                        <a class='user_avatar' href="{{ url_for('index.profile') }}">
                            <img src="{{user.image}}" title="{{ user.username }}"/>
                        </a>
                        <span class='user_name'><a class='dark' href="{{ url_for('index.profile') }}">{{ user.username }}</a></span>

                        <div class="space clearfix"></div>
                        <span class="signature">
                            “
                                {{ user.signature }}
                            ”
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('bp_topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>

                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
<div id="footer">
    <div id="footer_main">
        <div class="links">
            <a class="dark" href="https://github.com/HarpSun/BBS">源码地址</a>
            <p>Powerd By Flask</p>
        </div>
    </div>
</div>
{% endblock %}

templates/topic/new.html
{% extends "/base.html" %}
{% block title %}新话题{% endblock%}
{% block link %}
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
{% endblock %}
{% block script %}
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
{% endblock%}
{% block main %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            {% for b in bs %}
                {% if bid == b.id %}
                    <option value="{{ b.id }}" selected >{{ b.title }}</option>
                {% else %}
                    <option value="{{ b.id }}" >{{ b.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
{% endblock%}

{% block endscript %}
<script>
  (sfunction () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
{% endblock %}